version: '2'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: "kode-blog"
    container_name: KODE-Blog-db
    tty: true
    volumes:
      - "./db:/var/lib/mysql"
  app:
    build:
      context: .
    container_name: KODE-Blog
    ports:
      - "8080:8080"
    tty: true
    restart: always
    depends_on:
      - db