version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: "kode-blog"
    container_name: KODE-Blog-db
    tty: true
    volumes:
      - "KODE-DB:/var/lib/mysql"
  app:
    build:
      context: .
    container_name: KODE-Blog
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always

    depends_on:
      - db
volumes:
  KODE-DB:
