version: '3'
services:
  db:
    image: mysql:latest
    env_file:
      - .db-env
    container_name: KODE-Blog-db
    tty: true
    volumes:
      - "KODE-DB:/var/lib/mysql"
  app:
    build:
      context: .
      args:
        BUILD_TIME: unspecified
        GIT_COMMIT: unspecified
    image: my_webapp
    container_name: KODE-Blog
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
volumes:
  KODE-DB:
